Traceback (most recent call last):
  File "C:\meditrack\meditrack\meditrack\manage.py", line 22, in <module>
    main()
  File "C:\meditrack\meditrack\meditrack\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\meditrack\env\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\meditrack\env\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\meditrack\env\Lib\site-packages\django\core\management\base.py", line 416, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\meditrack\env\Lib\site-packages\django\core\management\base.py", line 460, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\meditrack\meditrack\meditrack\core\management\commands\check_reminders.py", line 60, in handle
    self.stdout.write(
  File "C:\meditrack\env\Lib\site-packages\django\core\management\base.py", line 181, in write
    self._out.write(style_func(msg))
  File "C:\Program Files\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u23f0' in position 0: character maps to <undefined>
Sent reminder to jc.melendrezz for Paracetamol (3/3)
Sent reminder to jc.melendrezz for Ibuprofen (1/2)
Sent reminder to jc.melendrezz for Ibuprofen (2/2)
Sent reminder to jc.melendrezz for Ibuprofen (2/2)
Sent reminder to jc.melendrezz for Ibuprofen (1/5)
Sent reminder to jc.melendrezz for Ibuprofen (2/5)
Sent reminder to jc.melendrezz for Ibuprofen (3/5)
Sent reminder to jc.melendrezz for Ibuprofen (4/5)
Sent reminder to jc.melendrezz for Paracetamol (4/5)
Sent reminder to jc.melendrezz for Ibuprofen (5/5)
Sent reminder to jc.melendrezz for Paracetamol (5/10)
Sent reminder to jc.melendrezz for Paracetamol (6/10)
Sent reminder to jc.melendrezz for Paracetamol (7/10)
Sent reminder to jc.melendrezz for Paracetamol (8/10)
Sent reminder to jc.melendrezz for Paracetamol (9/10)
Sent reminder to jc.melendrezz for Amoxycilin (1/3)
Sent reminder to jc.melendrezz for Paracetamol (10/10)
Sent reminder to jc.melendrezz for Amoxycilin (2/3)
Sent reminder to jc.melendrezz for Amoxycilin (3/3)
Traceback (most recent call last):
  File "C:\Users\Acer\meditrack_new\integ_final_project\meditrack\manage.py", line 22, in <module>
    main()
  File "C:\Users\Acer\meditrack_new\integ_final_project\meditrack\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Acer\meditrack_new\env\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\Acer\meditrack_new\env\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Acer\meditrack_new\env\Lib\site-packages\django\core\management\base.py", line 416, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Acer\meditrack_new\env\Lib\site-packages\django\core\management\base.py", line 460, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\meditrack_new\integ_final_project\meditrack\core\management\commands\check_reminders.py", line 55, in handle
    send_email(medication.user, med_reminder)
  File "C:\Users\Acer\meditrack_new\integ_final_project\meditrack\core\utils.py", line 57, in send_email
    send_mail(subject, message, from_email, recipient_list)
  File "C:\Users\Acer\meditrack_new\env\Lib\site-packages\django\core\mail\__init__.py", line 92, in send_mail
    return mail.send()
           ^^^^^^^^^^^
  File "C:\Users\Acer\meditrack_new\env\Lib\site-packages\django\core\mail\message.py", line 307, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\meditrack_new\env\Lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
                       ^^^^^^^^^^^
  File "C:\Users\Acer\meditrack_new\env\Lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-23506bc85c5sm13797495ad.14 - gsmtp')
Sent reminder to jc.melendrezz for Amoxycilin (1/3)
Sent reminder to jc.melendrezz for Amoxycilin (2/3)
Sent reminder to jc.melendrezz for Amoxycilin (3/3)
Sent reminder to jc.melendrezz for Paracetamol (1/3)
Sent reminder to jc.melendrezz for Paracetamol (2/3)
Sent reminder to jc.melendrezz for Paracetamol (3/3)
Traceback (most recent call last):
  File "C:\Users\Acer\meditrack_new\integ_final_project\meditrack\manage.py", line 22, in <module>
    main()
  File "C:\Users\Acer\meditrack_new\integ_final_project\meditrack\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Acer\meditrack_new\env\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\Acer\meditrack_new\env\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Acer\meditrack_new\env\Lib\site-packages\django\core\management\base.py", line 416, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Acer\meditrack_new\env\Lib\site-packages\django\core\management\base.py", line 460, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\meditrack_new\integ_final_project\meditrack\core\management\commands\check_reminders.py", line 24, in handle
    self.stdout.write("\u2705 Reset daily_meds_taken for all medications.")
  File "C:\Users\Acer\meditrack_new\env\Lib\site-packages\django\core\management\base.py", line 181, in write
    self._out.write(style_func(msg))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 0: character maps to <undefined>
